### ISSUE TITLE
Question of DIMES-MIS

### ISSUE THREAD

**Issue by wzever** [DIMESTeam/DIMES#10]
Thank you for the insightful work. I have set up the environment according to your instructions. However, I get confused when reproducing the MIS part on SATLIB instances. As for training, could you please offer some instruction on how to organize the training data files (e.g., in gpickle format)? Should I just place the gpickle files under `data_sat` directory? I find some lines in the file `solvers/intel_treesearch/NPHard/train_dimes_batched.py` reading files from `.mat` format files and a path `data_sat/train_mis/preprocessed/intel_treesearch` is accessed. Given the `data` and `data_sat` folders given in this repository are empty, I wonder the accurate way of placing my datasets and the processing pipeline for training and testing SATLIB data so that a successful execution of your provided script like `solve_intel_dimes_sat.sh` can be ensured. I really appreciate the authors' delicately organized and wrapped coding, but I'm more than grateful if you could provide some explanation on the details of my above confusion. Looking forward to your reply!

**Comment by q-rz** [comment]
Thank you for your interest in our work!

The training data folder is specified in the `--input_folder` argument. For example, if you use the command in [`MIS/scripts/solve_intel_dimes_sat.sh`](https://github.com/DIMESTeam/DIMES/blob/main/MIS/scripts/solve_intel_dimes_sat.sh), then you should put the training data into the `data_sat/train_mis` folder.

Please feel free to let us know if you have any questions.
