### ISSUE TITLE
some problems when running the code

### ISSUE THREAD

**Issue by AlexAuthor7** [DIMESTeam/DIMES#2]
After reading your paper, I found that your work is very meaningful, but I encountered some problems when running the code.
When running command       pip install ./torch_sampling    ，The following error occurs：
```
error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> torch-sampling
```

We think it is because GCC version does not match, We would like to know which version of GCC you are using.

**Comment by q-rz** [comment]
Hi! Thank you for your interest in our work.

We used GCC 7.5.0 on Ubuntu 18.04.

If you have other questions, please feel free to reach out.

**Comment by AlexAuthor7** [comment]
Thank you for your reply. Later, we found out that the name of some functions had changed in the new version due to the update of torch_scatter. Thanks again for your reply.

**Comment by AlexAuthor7** [comment]
Thank you for your reply. We later found that in the new version, due to an update to torch_scatter, some of the function names had changed, which caused errors. Thank you again for your reply.

**Comment by q-rz** [comment]
Thank you for your feedback! I will add a notice in readme.
