### ISSUE TITLE
Segmentation fault Problem while running MCTS_10000

### ISSUE THREAD

**Issue by lutk3029** [DIMESTeam/DIMES#3]
When I run MCTS_10000 with the default setting (./solve.sh 10000 16 16), I met the error "Segmentation fault". I think it's due to the undersized CPU I'm using as it works fine on both 1000 and 500 points.
I want to know what type of CPU you are running and how much memory is needed for the program to run normally.
I would be very grateful if you could give me some advice。

**Comment by q-rz** [comment]
Thank you for your interest in our work. In our experiments, MCTS was run on Intel Xeon Gold 6230 80-core CPU. You may refer to Appendix D.1 for hardware configuration.

If you run out of CPU memory, you may reduce the number of threads (the 3rd argument). Please make sure that it divides 16. For example,

```bash
./solve.sh 10000 16 4
```

If you have other questions, please do not hesitate to let me know.
