### ISSUE TITLE
Request for Heatmaps in Tables 1

### ISSUE THREAD

**Issue by xyfffff** [DIMESTeam/DIMES#5]
Hi Ruizhong,

Very appreciate that you have shared the source codes, which are immensely helpful. However, to fully reproduce your paper's results, could you also share the Heatmaps generated for the datasets in Tables 1? Access to these Heatmaps would be incredibly valuable for my reproducing, since I am facing some problems about installing the required packages.

Thank you for your time and assistance, and for your contributions to the field. I look forward to your response.

Best regards,
Yifan

**Comment by q-rz** [comment]
Hi Yifan,

Thank you for your interest in our work! I've uploaded the heatmaps of DIMES \& DIMES+AS to the folder `/TSP/TSP-KNN/output`. If you have any questions, please feel free to let me know.

Best regards,
Ruizhong

P.S. Beware that the TSP-10000 heatmaps are large after unzipping (around 900MB per graph).
