### ISSUE TITLE
error: utils

### ISSUE THREAD

**Issue by zhumingpassional** [DIMESTeam/DIMES#9]
Dear Madam/Sir,
  When I run the MIS, it raises errors. could pls solve this problem?

bash scripts/solve_intel_dimes_er.sh

CondaError: Run 'conda init' before 'conda activate'

Traceback (most recent call last):
  File "main.py", line 397, in <module>
    main(args)
  File "main.py", line 285, in main
    _train_or_solve(args)
  File "main.py", line 54, in _train_or_solve
    from solvers.intel_treesearch import IntelTreesearch
  File "/home/zhuming/code/DIMES-main/MIS/solvers/intel_treesearch.py", line 13, in <module>
    from utils import launch_python_script_in_conda_env

**Comment by q-rz** [comment]
Thanks for your interest in our work!

The MIS code was forked from [this repo](https://github.com/MaxiBoether/mis-benchmark-framework). We are not absolutely certain about what happened to their code in your case, but we will try to help.

It seems that the code needs to be run in a conda environment. Would you mind if you provide more detail about how you ran the code?

**Comment by zhumingpassional** [comment]
args.output_folder.mkdir(parents=True, exist_ok=True)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'output_folder'

I run the main.py of MIS, it failed.  could you pls help me for it?

**Comment by q-rz** [comment]
The argument `output_folder` is under a subparser. It seems that you did not choose the correct subparser. If you call `main.py`, please specify which subparser you want to use. For example, if you want to call `solve`, please run:
```bash
python3 main.py solve --output_folder=... {and other arguments here}
```

**Comment by zhumingpassional** [comment]
I tried, but it still failed. 
could you pls revise it so that it works？

**Comment by q-rz** [comment]
Could you provide more information about how you ran the code (for example, the exact command you used to run the code)? This will help us identify the issue.

**Comment by zhumingpassional** [comment]
there are too many params to write if using parsing in the terminal. I hope it works if running the .py directly.

**Comment by q-rz** [comment]
There are two possible solutions:

1. Writing a bash script that includes the params. Then you can simply run the script in the terminal. This is what we did in our experiments.
2. Adding default values of the params in the python file. Then you can simply run the python file without explicitly specifying all params in the terminal.
